import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";
import "./lib/fontawesome"
const roboto = Roboto({ subsets: ["latin"],weight:["400","700"] });

export const metadata: Metadata = {
  title: "Rikkei Academy",
  description: "Generated by create next app",
  icons:{
    icon:"https://learn.rikkeiacademy.com/favicon.ico.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
